<?php

return [
    'kubota_user' => 'kubota',
    'ind_user' => 'independent',
    'temporary_password_chars' => '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',
    'data_table_starting_column_index' => 0,
    'data_table_starting_column_index_order' => 'desc',
    'data_table_per_page' => 20,
    'toastr_time_out' => 3000,
    'ajax_xhr_error_status' => 419,
    'date_format_ymd' => 'Y/m/d',
    'text_display_max_length' => 20,
    'datepicker_date_format' => 'yy/mm/dd',
    'date_picker_starting_year' => '1950',
    'csv_chunk_size' => 1000,
    'csv_starting_cell' => 'A1',
    'csv_serial_number' => 1,
    'csv_encode_type' => 'UTF-8',
    'default_column_order'=>'id',
    'default_column_sort_order'=>'desc',
    'get_type_count' => 'count',
    'active' => 0,
    'inactive' => 1,
    'ind_user_group_id' => 6,
    'kubota_user_guid_length' => 10,
    'ind_user_guid_length' => 64,
    'primary_user' => 1,
    'language_japanese' => 'ja',
    'language_english' => 'en',
    'public' => 1,
    'private' => 0,
    'pending' => 2,
    'is_admin' => 1,
    'full_width_text_display_max_length' => 10,
    'telephonw_text_display_max_length' => 11,
    'max_number_of_files' => 3,
    'video_upload_max_size_in_mb' => 500,
    'files_max_size_in_mb' => 100,
    'dashboard_list_limit' => 5,
    'inquiry_form_mime_types' => 'gif,tif,png,jpg,pdf,doc,docx,xls,xlxs,ppt,pptx,txt,csv',
    'inquiry_from_upload_size_limit' => '5MB',
    'cookie_life_time' => 1440, //1 Day
    'faq_text_display_max_length' => 100,
];
