<?php

return [
    'kubota_user' => 1,
    'ind_user' => 2,
    'temporary_password_chars' => '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ',
    'data_table_starting_column_index' => 0,
    'data_table_starting_column_index_order' => 'desc',
    'data_table_per_page' => 20,
    'toastr_time_out' => 3000,
    'ajax_xhr_error_status' => 419,
    'date_format_ymd' => 'Y/m/d',
    'text_display_max_length' => 20,
    'datepicker_date_format' => 'yy/mm/dd',
    'date_picker_starting_year' => '1950',
    'csv_chunk_size' => 1000,
    'csv_starting_cell' => 'A1',
    'csv_serial_number' => 1,
    'csv_encode_type' => 'UTF-8',
    'default_column_order'=>'id',
    'default_column_sort_order'=>'desc',
    'get_type_count' => 'count',
    'active' => 0,
    'inactive' => 1,
    'ind_user_group_id' => 6,
];
